import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../components/Layout'


export default function Home() {


  return (
    <>
      <Head>
        <title>Balai Standardisasi dan Pelayanan Jasa Industri Palembang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="w-full h-screen bg-[rgb(242,242,242)] overflow-hidden">
            <div className="absolute w-full h-full bg-black opacity-30 z-[4]"></div>
            {/* Gambar halaman utama */}
            <section id='hero-image' className='relative w-full h-full'>
              <Image src={'/image/bspji-palembang.jpg'} alt='bspji-palembang' fill/>
            </section>

            {/* Pencarian Buku */}
            <section className="absolute px-4 py-8 md:p-6 md:pb-14 left-6 right-6 md:left-[18%] md:right-[18%] top-[56%] bg-white rounded-xl space-y-5 z-10">
              <h1 className="text-xl text-left font-bold">
                🔍 Cari Koleksi
              </h1>
              <div className="flex w-full space-x-2">
                <input
                  type="search"
                  required={true}
                  placeholder="Cari berdasarkan kata kunci..."
                  className="input w-full py-3"
                />
                <button
                  type="submit"
                  className="btn-search px-6"
                >
                  Cari
                </button>
              </div>
            </section>
            {/* Akhir pencarian buku */}

          </div>
          <div className="container">
            <h1 className='mt-[200px]'>Hello World</h1>
          </div>
        </Layout>
      </main>
    </>
  )
}
